package org.iottree.core.store.gdb.autofit;

import org.iottree.core.store.gdb.autofit.DbSql.SqlAndInputVals;
import org.iottree.core.store.gdb.connpool.DBType;
import org.iottree.core.util.Convert;
import org.iottree.core.util.xmldata.XmlVal;
import org.iottree.core.util.xmldata.XmlVal.XmlValType;

public class DBSqlSQLite extends DbSql
{

	public DBType getDBType()
	{
		return DBType.sqlite;
	}

	public String getSqlType(XmlValType vt, int maxlen)
	{
		if(vt==XmlValType.vt_int32)
		{
			return "INTEGER";
		}
		else if(vt==XmlValType.vt_byte_array)
		{//blob
			return "blob";
		}
		else if(vt==XmlValType.vt_date)
		{
			return "timestamp";
		}
		else if(vt==XmlValType.vt_double)
		{
			return "real";
		}
		else if(vt==XmlValType.vt_float)
		{
			return "real";
		}
		else if(vt==XmlValType.vt_int64)
		{
			return "BIGINT";
		}
		else if(vt==XmlValType.vt_int16)
		{
			return "SMALLINT";
		}
		else if(vt==XmlValType.vt_byte)
		{
			return "TINYINT";
		}
		else if(vt==XmlValType.vt_string)
		{
			if(maxlen<=0)
				throw new IllegalArgumentException("max len must >0");
			
			if(maxlen==Integer.MAX_VALUE)
			{//clob
				return "TEXT";
			}
			
			return "varchar("+maxlen+")";
		}
		else if(vt==XmlValType.vt_bool)
		{
			return "bit";
		}
		else// if(vt==XmlValType.vt_xml_schema)
		{
			throw new IllegalArgumentException("unsupported val type="+vt);
		}
	}
	

	@Override
	protected StringBuffer[] constructCreationTable(JavaTableInfo jti)
	{
		StringBuffer tmpsb = new StringBuffer();
		tmpsb.append("create table ").append(jti.getTableName())
			.append("(");
		
		JavaColumnInfo pkcol = jti.getPkColumnInfo() ;
		boolean bfirst = true ;
		if(pkcol!=null)
		{
			if(pkcol.isAutoVal() && pkcol.getValType()!=XmlVal.XmlValType.vt_string)
			{
				tmpsb.append(pkcol.getColumnName()).append(" ")
					.append(getSqlType(pkcol.getValType(),pkcol.getMaxLen()))
					.append(" GENERATED BY DEFAULT AS IDENTITY primary key");
			}
			else
			{
				tmpsb.append(pkcol.getColumnName()).append(" ")
				.append(getSqlType(pkcol.getValType(),pkcol.getMaxLen()))
				.append(" primary key");
			}
			bfirst = false ;
		}
		
		for(JavaColumnInfo tmpjci:jti.getNorColumnInfos())
		{
			if(bfirst) bfirst=false;
			else
				tmpsb.append(',') ;
//			if(tmpsb.charAt(tmpsb.length()-1)!=',')
//				tmpsb.append(',');
			
			tmpsb.append(tmpjci.getColumnName()).append(" ")
				.append(getSqlType(tmpjci.getValType(),tmpjci.getMaxLen()));
			
			String defvstr = tmpjci.getDefaultValStr() ;
			if(defvstr!=null)
			{
				XmlVal.XmlValType vt = tmpjci.getValType();
				if(vt==XmlVal.XmlValType.vt_string)
					tmpsb.append(" default '").append(defvstr).append("'");
				else if(vt==XmlVal.XmlValType.vt_bool)
				{
					if("1".equals(defvstr)||"true".equals(defvstr))
						tmpsb.append(" default true");
					else
						tmpsb.append(" default false");
				}
				else if(!defvstr.equals(""))
					tmpsb.append(" default ").append(defvstr);
			}
		}
		
		tmpsb.append(")");
		return new StringBuffer[]{tmpsb} ;
	}
	
	@Override
	protected StringBuffer[] constructCreationTableDistributedMode1(JavaTableInfo jti)
	{
		StringBuffer tmpsb = new StringBuffer();
		tmpsb.append("create table ").append(jti.getTableName())
			.append("(");
		
		tmpsb.append("_ProxyId integer,");
		
		JavaColumnInfo pkcol = jti.getPkColumnInfo() ;
		if(pkcol!=null)
		{
			if(pkcol.isAutoVal())
			{
				tmpsb.append(pkcol.getColumnName()).append(" ")
					.append(getSqlType(pkcol.getValType(),pkcol.getMaxLen()))
					.append(" GENERATED BY DEFAULT AS IDENTITY");
			}
			else
			{
				tmpsb.append(pkcol.getColumnName()).append(" ")
				.append(getSqlType(pkcol.getValType(),pkcol.getMaxLen()));
			}
		}
		
		for(JavaColumnInfo tmpjci:jti.getNorColumnInfos())
		{
			if(tmpsb.charAt(tmpsb.length()-1)!=',')
				tmpsb.append(',');
			
			tmpsb.append(tmpjci.getColumnName()).append(" ")
				.append(getSqlType(tmpjci.getValType(),tmpjci.getMaxLen()));
			
			String defvstr = tmpjci.getDefaultValStr() ;
			if(defvstr!=null)
			{
				XmlVal.XmlValType vt = tmpjci.getValType();
				if(vt==XmlVal.XmlValType.vt_string)
					tmpsb.append(" default '").append(defvstr).append("'");
				else if(!defvstr.equals(""))
					tmpsb.append(" default ").append(defvstr);
			}
		}
		
		tmpsb.append(")");
		return new StringBuffer[]{tmpsb} ;
	}
	
	@Override
	protected StringBuffer[] constructCreationTableDistributedMode2(JavaTableInfo jti)
	{
		StringBuffer tmpsb = new StringBuffer();
		tmpsb.append("create table ").append(jti.getTableName())
			.append("(");
		
		JavaColumnInfo pkcol = jti.getPkColumnInfo() ;
		if(pkcol==null)
		{
			throw new RuntimeException("distributed mode2 must has pk column!") ;
		}
		
		if(pkcol.isAutoVal())
		{
			tmpsb.append(pkcol.getColumnName()).append(" ")
				.append(getSqlType(pkcol.getValType(),pkcol.getMaxLen()))
				.append(" GENERATED BY DEFAULT AS IDENTITY primary key");
		}
		else
		{
			tmpsb.append(pkcol.getColumnName()).append(" ")
			.append(getSqlType(pkcol.getValType(),pkcol.getMaxLen()))
			.append(" primary key");
		}
		
		for(JavaColumnInfo tmpjci:jti.getNorColumnInfos())
		{
			if(tmpsb.charAt(tmpsb.length()-1)!=',')
				tmpsb.append(',');
			
			tmpsb.append(tmpjci.getColumnName()).append(" ")
				.append(getSqlType(tmpjci.getValType(),tmpjci.getMaxLen()));
			
			String defvstr = tmpjci.getDefaultValStr() ;
			if(defvstr!=null)
			{
				XmlVal.XmlValType vt = tmpjci.getValType();
				if(vt==XmlVal.XmlValType.vt_string)
					tmpsb.append(" default '").append(defvstr).append("'");
				else if(!defvstr.equals(""))
					tmpsb.append(" default ").append(defvstr);
			}
		}
		
//		����ʱ�����
		tmpsb.append(",_ServerUpdateDT bigint") ;
		
		tmpsb.append(")");
		return new StringBuffer[]{tmpsb} ;
	}
	
	public StringBuffer constructAddColumnToTable(JavaTableInfo jti,JavaColumnInfo jci,String after_colname)
	{
		StringBuffer tmpsb = new StringBuffer();
		tmpsb.append("ALTER TABLE ")
			.append(jti.getTableName())
			.append(" ADD COLUMN ").append(jci.getColumnName()).append(" ")
			.append(getSqlType(jci.getValType(),jci.getMaxLen()));
		return tmpsb;
	}
	
	/**
	 * ���ع���ɾ��������sqlָ�ȱʡ��ʽ��drop index idxn if exists
	 * @param jti
	 * @param jci
	 * @return
	 */
	public StringBuffer constructDropIndex(JavaTableInfo jti,JavaColumnInfo jci)
	{
		StringBuffer tmpsb = new StringBuffer();
		tmpsb.append("DROP INDEX ")
			.append(calIndexName(jti,jci)).append(" IF EXISTS");
		return tmpsb ;
	}
	
//	private String getPkSeqName(JavaTableInfo jti)
//	{
//		JavaColumnInfo pkcol = jti.getPkColumnInfo();
//		if(pkcol==null)
//			return null ;
//		
//		return "dx_seq_"+jti.getTableName()+"_"+pkcol.getColumnName() ;
//	}
//	@Override
//	public List<String> getCreationSqls(JavaTableInfo jti)
//	{
//		List<String> rets = super.getCreationSqls(jti);
//		
//		String seqn = getPkSeqName(jti) ;
//		if(seqn==null)
//			return rets ;
//		
//		//����sequence
//		rets.add("CREATE SEQUENCE "+seqn+" AS BIGINT START WITH 1");
//		return rets ;
//	}
	
	public StringBuffer[] getInsertSqlWithNewIdReturn(JavaTableInfo jti,String tablename)
	{
		StringBuffer tmpsb = new StringBuffer();
		JavaColumnInfo[] jcis = jti.getNorColumnInfos() ;
		if(Convert.isNullOrEmpty(tablename))
			tablename = jti.getTableName() ;
		tmpsb.append("insert into ").append(tablename)
			.append(" (").append(jcis[0].getColumnName());
		
		for(int i = 1 ; i < jcis.length ; i ++)
		{
			tmpsb.append(",").append(jcis[i].getColumnName());
		}
		tmpsb.append(") values (?");
		for(int i = 1 ; i < jcis.length ; i ++)
		{
			tmpsb.append(",?");
		}
		tmpsb.append(")");
		
		StringBuffer sbgetid=  new StringBuffer();
		sbgetid.append("values IDENTITY_VAL_LOCAL()");
		
		return new StringBuffer[]{tmpsb,sbgetid} ;
	}

	@Override
	public SqlAndInputVals getSelectSqlWithPage(JavaTableInfo jti,
			boolean distinct,String[] selectcols,
			String wherestr,Object[] input_vals,
			String groupby,String orderbystr,
			int pageidx,int pagesize)
	{
		String limstr = "limit " + pageidx * pagesize + " " + pagesize;
		StringBuffer sqlsb = new StringBuffer();
		sqlsb.append("select ");
		sqlsb.append(limstr).append(" ");
		if(distinct)
			sqlsb.append("DISTINCT ");

		if(selectcols==null||selectcols.length<=0)
		{
			JavaColumnInfo pkcol = jti.getPkColumnInfo();
			JavaColumnInfo[] norcols = jti.getNorColumnInfos() ;
			int i = 0 ;
			if(pkcol!=null)
			{
				sqlsb.append(pkcol.getColumnName()) ;
			}
			else
			{
				sqlsb.append(norcols[0].getColumnName());
				i ++ ;
			}
			
			for(;i<norcols.length ; i ++)
			{
				sqlsb.append(',').append(norcols[i].getColumnName());
			}
		}
		else
		{
			sqlsb.append(selectcols[0]);
			for(int i = 1 ; i < selectcols.length ; i ++)
			{
				sqlsb.append(',').append(selectcols[i]);
			}
		}

		sqlsb.append(" from ").append(jti.getTableName());
		if(wherestr!=null&&!(wherestr=wherestr.trim()).equals(""))
		{
			sqlsb.append(" where ").append(wherestr);
		}

		if(groupby!=null&&!(groupby=groupby.trim()).equals(""))
		{
			sqlsb.append(" group by ").append(groupby);
		}
		
		if(orderbystr!=null&&!(orderbystr=orderbystr.trim()).equals(""))
		{
			sqlsb.append(" order by ").append(orderbystr);
		}
		
		return new SqlAndInputVals(sqlsb,input_vals);
	}
}
